### ISSUE TITLE
1.21.1 NeoForge Dedicated Server bug 

### ISSUE THREAD

**Issue by Zelioth** [Noonday/Simplywands#1]
[crash-2024-08-27_16.05.52-fml.txt](https://github.com/user-attachments/files/16769610/crash-2024-08-27_16.05.52-fml.txt)

The crash report explains it all haha

minecraft 1.21.1
Neoforge 21.1.31

**Comment by Noonday** [comment]
Hello, thank you for reporting this.
I had honestly forgotten all about thinking about the server side.

Anyway, a temporary fix will be posted on Curseforge soon as a 1.2
this fix will let you be able to play with the mod on servers, but the Ore-Locator Wand will not work.
